//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Presentation.wwwroot.Resources.Reminder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Presentation.wwwroot.Resources.Reminder.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن یادآور.
        /// </summary>
        public static string AddReminder {
            get {
                return ResourceManager.GetString("AddReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش یادآور.
        /// </summary>
        public static string EditReminder {
            get {
                return ResourceManager.GetString("EditReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست یادآورها.
        /// </summary>
        public static string ReminderList {
            get {
                return ResourceManager.GetString("ReminderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان .
        /// </summary>
        public static string ReminderTitle {
            get {
                return ResourceManager.GetString("ReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار یادآور.
        /// </summary>
        public static string Repeated {
            get {
                return ResourceManager.GetString("Repeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال به.
        /// </summary>
        public static string SendTo {
            get {
                return ResourceManager.GetString("SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
    }
}
