//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Presentation.wwwroot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mesages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mesages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Presentation.wwwroot.Resources.Mesages", typeof(Mesages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه برنامه با خطا مواجه شد ، لطفا با پشتیبانی تماس بگیرید..
        /// </summary>
        public static string AnErrorHasAccuredInTheOperation {
            get {
                return ResourceManager.GetString("AnErrorHasAccuredInTheOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای آپلود کلیک کنید.
        /// </summary>
        public static string ClickForUpload {
            get {
                return ResourceManager.GetString("ClickForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف با موفقیت انجام شد ..
        /// </summary>
        public static string DeleteSuccessfullyApplied {
            get {
                return ResourceManager.GetString("DeleteSuccessfullyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا برخی از شماره های همراه وارد شده تکراری هستند !.
        /// </summary>
        public static string DoesNotAlllowedToRegisterRepeatedMobiles {
            get {
                return ResourceManager.GetString("DoesNotAlllowedToRegisterRepeatedMobiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا برخی از شماره تلفن های وارد شده تکراری هستند !.
        /// </summary>
        public static string DoesNotAlllowedToRegisterRepeatedTels {
            get {
                return ResourceManager.GetString("DoesNotAlllowedToRegisterRepeatedTels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا برخی از فیلدهای شماره همراه خالی است.
        /// </summary>
        public static string FillTheEmptyFieldMobiles {
            get {
                return ResourceManager.GetString("FillTheEmptyFieldMobiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا برخی از فیلدهای شماره تلفن خالی است .
        /// </summary>
        public static string FillTheEmptyFieldTels {
            get {
                return ResourceManager.GetString("FillTheEmptyFieldTels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییرات با موفقیت ثبت شد .
        /// </summary>
        public static string TheActionEndedWithSuccess {
            get {
                return ResourceManager.GetString("TheActionEndedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی شما به مدت 15 دقیقه مسدود شد لطفا بعد از این مدت دوباره تلاش کنید .
        /// </summary>
        public static string TryLoginMoreThanThreeTimes {
            get {
                return ResourceManager.GetString("TryLoginMoreThanThreeTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و یا رمز عبور وارد شده صحیح نیست !.
        /// </summary>
        public static string UserNamePasswordIsNotValid {
            get {
                return ResourceManager.GetString("UserNamePasswordIsNotValid", resourceCulture);
            }
        }
    }
}
