//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Presentation.wwwroot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mesages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mesages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Presentation.wwwroot.Resources.Mesages", typeof(Mesages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت ثبت نوبت دهی مشتری سالن را انتخاب کنید ..
        /// </summary>
        public static string AddPeopleToRegisterReservation {
            get {
                return ResourceManager.GetString("AddPeopleToRegisterReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه برنامه با خطا مواجه شد ، لطفا با پشتیبانی تماس بگیرید..
        /// </summary>
        public static string AnErrorHasAccuredInTheOperation {
            get {
                return ResourceManager.GetString("AnErrorHasAccuredInTheOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف این سرویس به مشتری اطمینان دارید ؟.
        /// </summary>
        public static string AreYouSureToDeleteCustomerService {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteCustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای آپلود کلیک کنید.
        /// </summary>
        public static string ClickForUpload {
            get {
                return ResourceManager.GetString("ClickForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله، حذف شود..
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشتری انتتخاب شده هیچ خدماتی انتخاب نشده است !.
        /// </summary>
        public static string CustomerServiceInfoIsEmpty {
            get {
                return ResourceManager.GetString("CustomerServiceInfoIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ نوبت دهی نمیتواند از تاریخ جاری کوچکتر باشد !.
        /// </summary>
        public static string DateReservationCanNotBeLessDateTimeNow {
            get {
                return ResourceManager.GetString("DateReservationCanNotBeLessDateTimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت حذف آیتم انتخاب شده اطمینان دارید ؟.
        /// </summary>
        public static string DeleteMessageQuestion {
            get {
                return ResourceManager.GetString("DeleteMessageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف با موفقیت انجام شد ..
        /// </summary>
        public static string DeleteSuccessfullyApplied {
            get {
                return ResourceManager.GetString("DeleteSuccessfullyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا برخی از شماره های همراه وارد شده تکراری هستند !.
        /// </summary>
        public static string DoesNotAlllowedToRegisterRepeatedMobiles {
            get {
                return ResourceManager.GetString("DoesNotAlllowedToRegisterRepeatedMobiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا برخی از شماره تلفن های وارد شده تکراری هستند !.
        /// </summary>
        public static string DoesNotAlllowedToRegisterRepeatedTels {
            get {
                return ResourceManager.GetString("DoesNotAlllowedToRegisterRepeatedTels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قصد خروج از این صفحه را دارید ؟.
        /// </summary>
        public static string DoYouWantToLeaveThisForm {
            get {
                return ResourceManager.GetString("DoYouWantToLeaveThisForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد های مورد نیاز را جهت افزودن شماره تلفن یا موبایل وارد نمایید ..
        /// </summary>
        public static string fillTelPhoneFieldsMessage {
            get {
                return ResourceManager.GetString("fillTelPhoneFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا برخی از فیلدهای شماره همراه خالی است.
        /// </summary>
        public static string FillTheEmptyFieldMobiles {
            get {
                return ResourceManager.GetString("FillTheEmptyFieldMobiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا برخی از فیلدهای شماره تلفن خالی است .
        /// </summary>
        public static string FillTheEmptyFieldTels {
            get {
                return ResourceManager.GetString("FillTheEmptyFieldTels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تمامی فیلدها را وارد نمایید !.
        /// </summary>
        public static string FillThisAddedServiceItem {
            get {
                return ResourceManager.GetString("FillThisAddedServiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ثبت شخص هیچ معرفی انتخاب نشده است آیا میخواهید ادامه دهید؟.
        /// </summary>
        public static string ForThisCustomerHasNotRegisterAnyIntroducePeople {
            get {
                return ResourceManager.GetString("ForThisCustomerHasNotRegisterAnyIntroducePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای منوی انتخاب شده یک یا چند زیر منو فعال است ابتدا زیر منوها را غیر فعال کنید!.
        /// </summary>
        public static string ForThisMenuThereAreSomeActiveSubMenu {
            get {
                return ResourceManager.GetString("ForThisMenuThereAreSomeActiveSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این نوبت دهی قبلا  صورتحساب به ثبت رسیده است.
        /// </summary>
        public static string ForThisReservationHasRegisterdCheque {
            get {
                return ResourceManager.GetString("ForThisReservationHasRegisterdCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقادیر ازتاریخ تا تاریخ را وارد کنید !.
        /// </summary>
        public static string FromDateAndToDateMenuAccessInNull {
            get {
                return ResourceManager.GetString("FromDateAndToDateMenuAccessInNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد دستی وارد شده شخص قبلا ثبت شده است !.
        /// </summary>
        public static string ManaulCodeIsDuplicated {
            get {
                return ResourceManager.GetString("ManaulCodeIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این شخص شماره تلفن وارد نشده آیا میخواهید ادامه دهید ؟.
        /// </summary>
        public static string NoTelPhoneEnteredForPeople {
            get {
                return ResourceManager.GetString("NoTelPhoneEnteredForPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یک سرویس باید به مشتری اختصاص داده شود !.
        /// </summary>
        public static string OneServiceShouldBeThereAtLeast {
            get {
                return ResourceManager.GetString("OneServiceShouldBeThereAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام معرف و نام شخص نمی تواند هم نام باشد !.
        /// </summary>
        public static string PeopleCanNotBeSameAsIntroductionPeople {
            get {
                return ResourceManager.GetString("PeopleCanNotBeSameAsIntroductionPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال ....
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامک ثبت نوبت را به مشتری ارسال کن .
        /// </summary>
        public static string SendSMSToCustomerForReservatin {
            get {
                return ResourceManager.GetString("SendSMSToCustomerForReservatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییرات با موفقیت ثبت شد .
        /// </summary>
        public static string TheActionEndedWithSuccess {
            get {
                return ResourceManager.GetString("TheActionEndedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت و زمان وارد شده صحیح نیست.
        /// </summary>
        public static string TheEnterTimeHourIsNotValid {
            get {
                return ResourceManager.GetString("TheEnterTimeHourIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت زمان وارد شده صحیح نیست !.
        /// </summary>
        public static string TheEnterTimeIsNotValid {
            get {
                return ResourceManager.GetString("TheEnterTimeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن وارد شده تکراری است !.
        /// </summary>
        public static string ThePhoneNumberIsDuplicated {
            get {
                return ResourceManager.GetString("ThePhoneNumberIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این مشتری در این تاریخ نوبت دهی شده است آیا میخواهید ادامه دهید ؟.
        /// </summary>
        public static string ThereIsAReservationOnThisDateForThisCustomer {
            get {
                return ResourceManager.GetString("ThereIsAReservationOnThisDateForThisCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا برخی از شماره تلفن ها تکراری است !.
        /// </summary>
        public static string ThereIsDuplicatedTelPhones {
            get {
                return ResourceManager.GetString("ThereIsDuplicatedTelPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کاربر انتخاب شده هیچ منوی فعالی انتخاب نشده است آیا ادامه می دهید ؟.
        /// </summary>
        public static string thereIsNotAnyActiveMenu {
            get {
                return ResourceManager.GetString("thereIsNotAnyActiveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این نوبت دهی سابقه وجود دارد و قابل ویرایش و حذف نیست .
        /// </summary>
        public static string ThereIsRecordHistoryForThisReservationRecordHistory {
            get {
                return ResourceManager.GetString("ThereIsRecordHistoryForThisReservationRecordHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این عملیات برگشت پذیر نیست....
        /// </summary>
        public static string ThisActionIsNotRestore {
            get {
                return ResourceManager.GetString("ThisActionIsNotRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فیلد الزامی است .
        /// </summary>
        public static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم انتخاب شده تکراری است !.
        /// </summary>
        public static string ThisItemHasAddedAleadyToServiceCustomer {
            get {
                return ResourceManager.GetString("ThisItemHasAddedAleadyToServiceCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان رزرو نوبت برای این تاریخ منقضی شده است !.
        /// </summary>
        public static string TimeReservationHasExpired {
            get {
                return ResourceManager.GetString("TimeReservationHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی شما به مدت 15 دقیقه مسدود شد لطفا بعد از این مدت دوباره تلاش کنید .
        /// </summary>
        public static string TryLoginMoreThanThreeTimes {
            get {
                return ResourceManager.GetString("TryLoginMoreThanThreeTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و یا رمز عبور وارد شده صحیح نیست !.
        /// </summary>
        public static string UserNamePasswordIsNotValid {
            get {
                return ResourceManager.GetString("UserNamePasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
