//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Presentation.wwwroot.Resources.Reservation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Presentation.wwwroot.Resources.Reservation.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند.
        /// </summary>
        public static string Clerk {
            get {
                return ResourceManager.GetString("Clerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات کارمند.
        /// </summary>
        public static string ClerkService {
            get {
                return ResourceManager.GetString("ClerkService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد مراجعه.
        /// </summary>
        public static string CountOfComing {
            get {
                return ResourceManager.GetString("CountOfComing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی مشتری.
        /// </summary>
        public static string CustomerFamily {
            get {
                return ResourceManager.GetString("CustomerFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مشتری .
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مشتری.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیعانه.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ازتاریخ نوبت دهی.
        /// </summary>
        public static string FromReservationDate {
            get {
                return ResourceManager.GetString("FromReservationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از ساعت.
        /// </summary>
        public static string FromTimeOrder {
            get {
                return ResourceManager.GetString("FromTimeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تسویه.
        /// </summary>
        public static string PaidType {
            get {
                return ResourceManager.GetString("PaidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی نوبت دهی.
        /// </summary>
        public static string ReservationSearch {
            get {
                return ResourceManager.GetString("ReservationSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد سیستمی نوبت.
        /// </summary>
        public static string ReservationSystemCode {
            get {
                return ResourceManager.GetString("ReservationSystemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات سالن.
        /// </summary>
        public static string SalonService {
            get {
                return ResourceManager.GetString("SalonService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع خدمات.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نوبت های امروز.
        /// </summary>
        public static string TodayReservationCount {
            get {
                return ResourceManager.GetString("TodayReservationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ نوبت دهی.
        /// </summary>
        public static string ToReservationDate {
            get {
                return ResourceManager.GetString("ToReservationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد مراجعه به سالن.
        /// </summary>
        public static string TotalComeInSalon {
            get {
                return ResourceManager.GetString("TotalComeInSalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سودآوری کل.
        /// </summary>
        public static string TotalIncomeForSalon {
            get {
                return ResourceManager.GetString("TotalIncomeForSalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع کل مبلغ نوبت ها.
        /// </summary>
        public static string TotalReservationPrice {
            get {
                return ResourceManager.GetString("TotalReservationPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع مبلغ نوبت های امروز.
        /// </summary>
        public static string TotalTodayReservationPrice {
            get {
                return ResourceManager.GetString("TotalTodayReservationPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا ساعت.
        /// </summary>
        public static string ToTimeOrder {
            get {
                return ResourceManager.GetString("ToTimeOrder", resourceCulture);
            }
        }
    }
}
