//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Presentation.wwwroot.Resources.Salon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Presentation.wwwroot.Resources.Salon.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه های حسابرسی.
        /// </summary>
        public static string AccontantCosts {
            get {
                return ResourceManager.GetString("AccontantCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابداری.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبلیغات.
        /// </summary>
        public static string Advertisment {
            get {
                return ResourceManager.GetString("Advertisment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابرسی.
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سود اقساط بانکی.
        /// </summary>
        public static string BankBenifit {
            get {
                return ResourceManager.GetString("BankBenifit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه استهلاک اموال.
        /// </summary>
        public static string BelongingsCosts {
            get {
                return ResourceManager.GetString("BelongingsCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه قبض.
        /// </summary>
        public static string BillIdentityNumber {
            get {
                return ResourceManager.GetString("BillIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پرداخت.
        /// </summary>
        public static string BillPayNumber {
            get {
                return ResourceManager.GetString("BillPayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبوض.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع قبض.
        /// </summary>
        public static string BillType {
            get {
                return ResourceManager.GetString("BillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح هزینه.
        /// </summary>
        public static string CostDescription {
            get {
                return ResourceManager.GetString("CostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه های شناسائی شده.
        /// </summary>
        public static string CostWithOutPayment {
            get {
                return ResourceManager.GetString("CostWithOutPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه های با پرداخت.
        /// </summary>
        public static string CostWithPayment {
            get {
                return ResourceManager.GetString("CostWithPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه استهلاک اموال.
        /// </summary>
        public static string Depriciation {
            get {
                return ResourceManager.GetString("Depriciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاوره مالی.
        /// </summary>
        public static string FinanceConsulting {
            get {
                return ResourceManager.GetString("FinanceConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جرائم مالیاتی.
        /// </summary>
        public static string FinancePenalties {
            get {
                return ResourceManager.GetString("FinancePenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنقلات.
        /// </summary>
        public static string Foods {
            get {
                return ResourceManager.GetString("Foods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ازتاریخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ازقیمت.
        /// </summary>
        public static string FromPrice {
            get {
                return ResourceManager.GetString("FromPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبدا.
        /// </summary>
        public static string FromTarget {
            get {
                return ResourceManager.GetString("FromTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گاز.
        /// </summary>
        public static string GasBill {
            get {
                return ResourceManager.GetString("GasBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه های عمومی و اداری.
        /// </summary>
        public static string GeneralAndOfficeCosts {
            get {
                return ResourceManager.GetString("GeneralAndOfficeCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازاریابی.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیک موتوری.
        /// </summary>
        public static string MotorCylePost {
            get {
                return ResourceManager.GetString("MotorCylePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر قبوض.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر.
        /// </summary>
        public static string OtherTransfer {
            get {
                return ResourceManager.GetString("OtherTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسته بندی.
        /// </summary>
        public static string Packing {
            get {
                return ResourceManager.GetString("Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برق.
        /// </summary>
        public static string PowerBill {
            get {
                return ResourceManager.GetString("PowerBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق و دستمزد.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی.
        /// </summary>
        public static string SalonCostGroup {
            get {
                return ResourceManager.GetString("SalonCostGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع هزینه.
        /// </summary>
        public static string SalonCostyType {
            get {
                return ResourceManager.GetString("SalonCostyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه های توزیع و فروش.
        /// </summary>
        public static string SellAndDistibuteCost {
            get {
                return ResourceManager.GetString("SellAndDistibuteCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسنپ.
        /// </summary>
        public static string Snapp {
            get {
                return ResourceManager.GetString("Snapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاکسی.
        /// </summary>
        public static string Taxi {
            get {
                return ResourceManager.GetString("Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string TelBill {
            get {
                return ResourceManager.GetString("TelBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقصد.
        /// </summary>
        public static string ToDestination {
            get {
                return ResourceManager.GetString("ToDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا قیمت.
        /// </summary>
        public static string ToPrice {
            get {
                return ResourceManager.GetString("ToPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوع هزینه های حسابداری.
        /// </summary>
        public static string TotalAccontantCosts {
            get {
                return ResourceManager.GetString("TotalAccontantCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع کل هزینه ها.
        /// </summary>
        public static string TotalAllPrice {
            get {
                return ResourceManager.GetString("TotalAllPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع هزینه های عمومی.
        /// </summary>
        public static string TotalPriceGeneralCost {
            get {
                return ResourceManager.GetString("TotalPriceGeneralCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع هزینه های توزیع و فروش.
        /// </summary>
        public static string TotalSellAndDistibuteCost {
            get {
                return ResourceManager.GetString("TotalSellAndDistibuteCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفت و آمد.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع رفت وآمد.
        /// </summary>
        public static string TransferType {
            get {
                return ResourceManager.GetString("TransferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار داری.
        /// </summary>
        public static string Warehosing {
            get {
                return ResourceManager.GetString("Warehosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آب.
        /// </summary>
        public static string WaterBill {
            get {
                return ResourceManager.GetString("WaterBill", resourceCulture);
            }
        }
    }
}
