//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Presentation.wwwroot.Resources.Personel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Presentation.wwwroot.Resources.Personel.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و ویرایش پرسنل.
        /// </summary>
        public static string AddPersonel {
            get {
                return ResourceManager.GetString("AddPersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت ساعت کاری .
        /// </summary>
        public static string AddPersonnelTimeWork {
            get {
                return ResourceManager.GetString("AddPersonnelTimeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت مرخصی.
        /// </summary>
        public static string AddPersonnelVacation {
            get {
                return ResourceManager.GetString("AddPersonnelVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع قرارداد.
        /// </summary>
        public static string AgreementType {
            get {
                return ResourceManager.GetString("AgreementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بد.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل تولد.
        /// </summary>
        public static string BirthOfPlace {
            get {
                return ResourceManager.GetString("BirthOfPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شناسنامه.
        /// </summary>
        public static string CertificateNumber {
            get {
                return ResourceManager.GetString("CertificateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسویه.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدارک.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پرسنل.
        /// </summary>
        public static string EditPersonel {
            get {
                return ResourceManager.GetString("EditPersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدام.
        /// </summary>
        public static string Employment {
            get {
                return ResourceManager.GetString("Employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ استخدام.
        /// </summary>
        public static string EmploymentDate {
            get {
                return ResourceManager.GetString("EmploymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عالی.
        /// </summary>
        public static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوب.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره بیمه.
        /// </summary>
        public static string InsuranceNumber {
            get {
                return ResourceManager.GetString("InsuranceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تاهل.
        /// </summary>
        public static string IsMaried {
            get {
                return ResourceManager.GetString("IsMaried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنلی.
        /// </summary>
        public static string PersonelCode {
            get {
                return ResourceManager.GetString("PersonelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پرسنل.
        /// </summary>
        public static string PersonelName {
            get {
                return ResourceManager.GetString("PersonelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پرسنل.
        /// </summary>
        public static string PersonnelInfromation {
            get {
                return ResourceManager.GetString("PersonnelInfromation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی پرسنل.
        /// </summary>
        public static string PersonnelLastName {
            get {
                return ResourceManager.GetString("PersonnelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت شغلی.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت ورود/خروج.
        /// </summary>
        public static string RegisterTime {
            get {
                return ResourceManager.GetString("RegisterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهارت ها.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مهارت.
        /// </summary>
        public static string SkillType {
            get {
                return ResourceManager.GetString("SkillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرخصی.
        /// </summary>
        public static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }
    }
}
