//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Presentation.wwwroot.Resources.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Presentation.wwwroot.Resources.General.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات زیر منوها.
        /// </summary>
        public static string ActionMenu {
            get {
                return ResourceManager.GetString("ActionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن کاربرجدید.
        /// </summary>
        public static string AddNewProfile {
            get {
                return ResourceManager.GetString("AddNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت شخص جدید.
        /// </summary>
        public static string AddPeople {
            get {
                return ResourceManager.GetString("AddPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت یادآور.
        /// </summary>
        public static string AddReminder {
            get {
                return ResourceManager.GetString("AddReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نوبت.
        /// </summary>
        public static string AddReservation {
            get {
                return ResourceManager.GetString("AddReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس .
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; همه &gt;&gt;.
        /// </summary>
        public static string AllItems {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبان گیری.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره های همراه تکراری را چک کن .
        /// </summary>
        public static string CheckRepeatedMobiles {
            get {
                return ResourceManager.GetString("CheckRepeatedMobiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن های تکراری را چک کن .
        /// </summary>
        public static string CheckRepeatedTels {
            get {
                return ResourceManager.GetString("CheckRepeatedTels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفتر تلفن.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن مخاطب جدید.
        /// </summary>
        public static string CreateNewContact {
            get {
                return ResourceManager.GetString("CreateNewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت شخص جدید.
        /// </summary>
        public static string CreateNewPeople {
            get {
                return ResourceManager.GetString("CreateNewPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت پرسنل.
        /// </summary>
        public static string CreateNewPersonel {
            get {
                return ResourceManager.GetString("CreateNewPersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصیص وظیفه.
        /// </summary>
        public static string CreateNewRole {
            get {
                return ResourceManager.GetString("CreateNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف خدمات سالن.
        /// </summary>
        public static string CreateNewSalonService {
            get {
                return ResourceManager.GetString("CreateNewSalonService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت محصول.
        /// </summary>
        public static string CreateProducts {
            get {
                return ResourceManager.GetString("CreateProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف میزهای آرایش.
        /// </summary>
        public static string CreateSalonDesk {
            get {
                return ResourceManager.GetString("CreateSalonDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف کاربر.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصیص نقش کاربر.
        /// </summary>
        public static string DefineUserRole {
            get {
                return ResourceManager.GetString("DefineUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اشخاص.
        /// </summary>
        public static string EditPeople {
            get {
                return ResourceManager.GetString("EditPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پروفایل.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کاربر.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشخاص فراموش شده.
        /// </summary>
        public static string ForgetPeople {
            get {
                return ResourceManager.GetString("ForgetPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات سالن.
        /// </summary>
        public static string GeneralSalonInfo {
            get {
                return ResourceManager.GetString("GeneralSalonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش درآمد.
        /// </summary>
        public static string IncomeReport {
            get {
                return ResourceManager.GetString("IncomeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات برنامه.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مجوز.
        /// </summary>
        public static string LisenceNumber {
            get {
                return ResourceManager.GetString("LisenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ورود .
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به برنامه.
        /// </summary>
        public static string LoginIntoApplication {
            get {
                return ResourceManager.GetString("LoginIntoApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منوهای اصلی.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت جاری :.
        /// </summary>
        public static string OnlineTime {
            get {
                return ResourceManager.GetString("OnlineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربرآنلاین:.
        /// </summary>
        public static string OnlineUser {
            get {
                return ResourceManager.GetString("OnlineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشخاص.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست اشخاص.
        /// </summary>
        public static string PeopleList {
            get {
                return ResourceManager.GetString("PeopleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش گیری.
        /// </summary>
        public static string PeopleReport {
            get {
                return ResourceManager.GetString("PeopleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل.
        /// </summary>
        public static string Personel {
            get {
                return ResourceManager.GetString("Personel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست پرسنل.
        /// </summary>
        public static string PersonelList {
            get {
                return ResourceManager.GetString("PersonelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; انتخاب کنید &gt;&gt;.
        /// </summary>
        public static string PleaseSelectOneItem {
            get {
                return ResourceManager.GetString("PleaseSelectOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش محصولات.
        /// </summary>
        public static string ProductsList {
            get {
                return ResourceManager.GetString("ProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایه.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت شماره های موبایل.
        /// </summary>
        public static string RegisterMobiles {
            get {
                return ResourceManager.GetString("RegisterMobiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت شماره های تلفن .
        /// </summary>
        public static string RegisterPhones {
            get {
                return ResourceManager.GetString("RegisterPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یادآور.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string ReminderList {
            get {
                return ResourceManager.GetString("ReminderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشات.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوبت دهی.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست نوبت ها.
        /// </summary>
        public static string ReservationList {
            get {
                return ResourceManager.GetString("ReservationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش نوبت ها.
        /// </summary>
        public static string ReservationReport {
            get {
                return ResourceManager.GetString("ReservationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگردانی نسخه پشتیبان.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وظایف.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست وظایف.
        /// </summary>
        public static string RoleList {
            get {
                return ResourceManager.GetString("RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string RowNum {
            get {
                return ResourceManager.GetString("RowNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سالن.
        /// </summary>
        public static string Salon {
            get {
                return ResourceManager.GetString("Salon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات سالن.
        /// </summary>
        public static string SalonInfo {
            get {
                return ResourceManager.GetString("SalonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت سالن.
        /// </summary>
        public static string SalonManager {
            get {
                return ResourceManager.GetString("SalonManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه.
        /// </summary>
        public static string Satuarday {
            get {
                return ResourceManager.GetString("Satuarday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو با نام - نام خانوادگی....
        /// </summary>
        public static string SearchWithFirstNameFullName {
            get {
                return ResourceManager.GetString("SearchWithFirstNameFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب لوگو.
        /// </summary>
        public static string SelectLogo {
            get {
                return ResourceManager.GetString("SelectLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش لیست مخاطبین.
        /// </summary>
        public static string ShowContactList {
            get {
                return ResourceManager.GetString("ShowContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش فایل.
        /// </summary>
        public static string ShowFile {
            get {
                return ResourceManager.GetString("ShowFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش اشخاص.
        /// </summary>
        public static string ShowPeople {
            get {
                return ResourceManager.GetString("ShowPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش لیست کاربران.
        /// </summary>
        public static string ShowUserList {
            get {
                return ResourceManager.GetString("ShowUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر منوها.
        /// </summary>
        public static string SubMenu {
            get {
                return ResourceManager.GetString("SubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکشنبه.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه شنبه.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجشنبه.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپلود فایل.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل.
        /// </summary>
        public static string UploadName {
            get {
                return ResourceManager.GetString("UploadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس پروفایل.
        /// </summary>
        public static string UserProfileImage {
            get {
                return ResourceManager.GetString("UserProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات کاربر.
        /// </summary>
        public static string UserSetting {
            get {
                return ResourceManager.GetString("UserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه.
        /// </summary>
        public static string Wensday {
            get {
                return ResourceManager.GetString("Wensday", resourceCulture);
            }
        }
    }
}
